name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images with custom names
        run: |
          docker build -t dream-vacations-frontend:latest ./frontend
          docker build -t dream-vacations-backend:latest ./backend

      - name: Start Docker containers
        run: |
          docker-compose -f ./docker-compose.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Execute PostgreSQL script
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: psql -h localhost -p 5432 -U postgres -f ./script_dreamvacations.sql
  
      - name: Download Trivy
        run: |
          sudo apt-get install -y wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker images with Trivy
        run: |
          trivy image --format table --output trivy_postgres_report.txt postgres:latest
          trivy image --format table --output trivy_frontend_image_report.txt dream-vacations-frontend:latest
          trivy image --format table --output trivy_backend_image_report.txt dream-vacations-backend:latest
          trivy image --format table --output trivy_adminer_image_report.txt adminer:latest

      - name: Commit Trivy scan results
        run: |
          git config --global user.name "Matt-Audu"
          git config --global user.email "simplymailmatthew7@gmail.com"
          git add trivy_*.json
          git commit -m "Add Trivy scan results"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
